name: MilletFlutterApp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  flutter_localizations: # 本地化
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.5.3  #屏幕适配
  fluttertoast: ^3.1.3  #吐司
  flutter_easyrefresh: ^2.0.8 #下拉刷新
  dio: ^3.0.9 #网络
  connectivity: ^0.4.4
  path_provider: ^1.3.0 #文件
  event_bus: ^1.1.0 #EventBus
  shared_preferences: ^0.5.6 #存储
  synchronized: '>=2.0.2 <4.0.0'
  provider: ^3.0.0 #状态更改
  permission_handler: ^3.3.0 #权限申请
  webview_flutter: ^0.3.21  #WebView
  url_launcher: ^5.4.5  #打开浏览器
  image_picker: ^0.6.6+1  #选择图片
  image_cropper: ^1.1.0    #图片剪切
  common_utils: ^1.2.1 #基础工具
  flutter_spinkit: ^4.0.0 #加载框
  flutter_swiper: ^1.1.6 #轮播图

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_black_back.png
    - assets/images/ic_login_top_logo.png
    - assets/images/gray-home.png
    - assets/images/select-home.png
    - assets/images/resource-noraml.png
    - assets/images/resource-select.png
    - assets/images/work-normal.png
    - assets/images/work-select.png
    - assets/images/mine-normal.png
    - assets/images/mine-select.png
    - assets/images/ic_homt_top_bg.png
    - assets/images/ic_top_1.png
    - assets/images/ic_top_2.png
    - assets/images/ic_top_3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
